### ISSUE TITLE
Log file

### ISSUE THREAD

**Issue by max28** [adrianslabu/tado_owda#1]
Could you consider to add some logs ? 

import logging

logging.basicConfig(format='%(asctime)s %(levelname)-8s %(message)s',filename="tado.log",level=logging.INFO)

def printm(message):
    global lastMessage
    if (message != lastMessage):
        lastMessage = message
        sys.stdout.write(message + "\n")
        logging.info (message)

thanks !

**Comment by max28** [comment]
May be with a boolean to active it ? And a variable for the location ?

**Comment by adrianslabu** [comment]
Hello,
I've done something similar in tado_aa, it includes open window detection and geofencing.
Thank you!
